---
# CentOS related tasks

- name: install MariaDB
  yum: 
    name:
      - mariadb-server
      - mariadb
      - python
      - python-setuptools
      - MySQL-python
    state: latest

- name: enable MariaDB
  systemd:
    name: mariadb
    enabled: true
