---
# tasks file for prep_mariadb

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: start MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove test db
  mysql_db:
    name: test
    state: absent
  
- name: create ccnet_db
  mysql_db:
    name: ccnet_db
    encoding: utf8
    state: present

- name: create seafile_db
  mysql_db:
    name: seafile_db
    encoding: utf8
    state: present

- name: create seahub_db
  mysql_db:
    name: seahub_db
    encoding: utf8
    state: present

- name: create seafile user
  mysql_user:
    name: seafile
    password: seafile
    priv:     "*.*:ALL,GRANT"
    state: present
