---
# tasks file for borgbackup

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: create dir backup
  file:
    path: /mnt/backup
    state: directory
    mode: u+w,g+w,o+w

- name: copy exports
  copy:
    src: exports
    dest: /etc/exports
    force: yes

- name: enable nfs-server
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: add static route for router
  shell: ip route add 10.20.30.0/24 via 192.168.50.5 dev eth1