---
# vars file for seafile
# seafile_archive: https://download.seadrive.org/seafile-server_7.0.5_x86-64.tar.gz
seafile_archive: https://s3.eu-central-1.amazonaws.com/download.seadrive.org/seafile-server_7.1.5_x86-64.tar.gz