---
# tasks file for seafile
- name: install pecakages for seafile
  yum:
    name:
      - python
      - python-setuptools
      - MySQL-python
      - python-urllib3
      - python-ldap
      - python3
      - python3-setuptools
      - python3-pip
    state: latest

- name: install pip files for seafile
  pip:
    name:
      - Pillow
      - pylibmc
      - captcha
      - jinja2
      - sqlalchemy
      - django-pylibmc
      - django-simple-captcha
      - python3-ldap
    executable: pip3.6

- name: create seafile directory
  file:
    path: /opt/seafile
    state: directory

- name: create installed directory
  file:
    path: /opt/seafile/installed
    state: directory

- name: download seafile archive
  get_url:
    url: "{{ seafile_archive }}"
    dest: /opt/seafile/installed/seafile-server.tar.gz

- name: extract seafile-server.tar.gz into /opt/seafile
  unarchive:
    src: /opt/seafile/installed/seafile-server.tar.gz
    dest: /opt/seafile
    remote_src: yes

- name: create seafile.service
  copy:
    src: seafile.service
    dest: /etc/systemd/system/seafile.service

- name: create seahub.service
  copy:
    src: seahub.service
    dest: /etc/systemd/system/seahub.service

- name: force systemd to reead configs
  systemd:
    daemon-reload: yes
