---
# tasks file for elastic_kibana

- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: copy elastic.repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: copy kibana.repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo

- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: install kibana
  yum:
    name: kibana
    state: present

- name: copy elasticsearch.yml
  copy: 
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    force: yes

- name: copy kibana.yml
  copy: 
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    force: yes

- name: start elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: start kibana
  systemd:
    name: kibana
    state: started
    enabled: yes
