---
# tasks file for prep_nginx

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: create nginx folders
  file:
    path: /etc/nginx/sites-available
    state: directory
  
- name: create nginx folders
  file:
    path: /etc/nginx/sites-enabled
    state: directory

# - name: nginx config for ssl
#   template:
#     src: ssl.conf.{{ ssl_certificate_type }}.j2
#     dest: /etc/nginx/conf.d/ssl.conf
#     owner: root
#     group: root
#     mode: 0644
#   notify: restart nginx

- name: copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    force: true

- name: copy seafile nginx config file
  copy:
    src: seafile.conf
    dest: /etc/nginx/sites-available/seafile.conf
    force: true

- name: create symbolic link seafile.conf
  file:
    src: /etc/nginx/sites-available/seafile.conf
    dest: /etc/nginx/sites-enabled/seafile.conf
    state: link

- name: start and enable nginx
  systemd:
    name:    nginx
    state:   started
    enabled: true