---
- hosts: web
  become: yes
  
  roles:
    - prepare_system
    - nginx
    - mariadb
    - seafile

- hosts: backup
  become: yes

  roles:
    - prepare_system
    - nfs-server

- hosts: router
  become: yes
  
  roles:
    - ip_forward
    - iptables
