---
- hosts: web
  become: yes
  
  roles:
    - prepare_system
    - elastic_beats
    - nginx
    - mariadb
    - seafile

- hosts: backup
  become: yes

  roles:
    - prepare_system
    - elastic_kibana
    - nfs-server
