---
- hosts: web
  become: yes
  
  roles:
    - prepare_system
    - nginx
    - mariadb
    - seafile
    - elastic_beats

- hosts: backup
  become: yes

  roles:
    - prepare_system
    - nfs-server
    - elastic_kibana

- hosts: router
  become: yes

  roles:
    - prepare_system
    - router
