---
# CentOS related tasks

- name: install epel-release
  yum:
    name: epel-release
    state: latest


# - name: update os
#   yum:
#     name: '*'
#     update_cache: true
#     state: latest

- name: install needed packages
  yum:
    name:
      - mc
      - vim
      - wget
      - rsync
      - nfs-utils
      - nfs4-acl-tools
      - setroubleshoot-server
      - setools-console
      - policycoreutils-python
      - policycoreutils-newrole
      - selinux-policy-mls
    state: latest
