---
# tasks file for prepare_system

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

# - name: sysctl vm.overcommit_memory=1
#   sysctl: 
#     name: vm.overcommit_memory
#     value: "1"
#     state: present
#     reload: true
#     sysctl_file: /etc/sysctl.conf

# - name: sysctl -w net.core.somaxconn=65535
#   sysctl:
#     name: net.core.somaxconn
#     value: "65535"
#     state: present
#     reload: true
#     sysctl_file: /etc/sysctl.conf
