---
# tasks file for elastic-beats

- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: copy elastic.repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install beats
  yum:
    name:
      - filebeat
      - metricbeat