---
# tasks file for elastic_beats

- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: copy elastic.repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install beats
  yum:
    name:
      - filebeat
      - metricbeat

- name: copy filebeat.yml
  copy: 
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    force: yes

- name: copy metricbeat.yml
  copy: 
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
    force: yes

- name: enable modules filebeat
  shell: filebeat modules enable system nginx

# - name: setup filebeat
#   shell: filebeat setup -e

# - name: setup metricbeat
#   shell: metricbeat setup -e

- name: start filebeat
  systemd:
    name: filebeat
    state: started
    enabled: yes

- name: start metricbeat
  systemd:
    name: metricbeat
    state: started
    enabled: yes
